// 66 questions organized by section
const surveyQuestions = {
  1: {
    title: 'Religious Practice & Observance',
    questions: [
      {
        id: 1,
        question: 'How would you describe your current level of religious observance?',
        type: 'enum',
        options: [
          { value: 'very_observant', label: 'Very observant' },
          { value: 'observant', label: 'Observant' },
          { value: 'moderately_observant', label: 'Moderately observant' },
          { value: 'somewhat_observant', label: 'Somewhat observant' },
          { value: 'minimally_observant', label: 'Minimally observant' },
        ],
      },
      {
        id: 2,
        question: 'What does daily tefillah look like for you on a typical weekday?',
        type: 'enum',
        options: [
          { value: 'minyan_daily', label: 'Minyan daily' },
          { value: 'minyan_often', label: 'Minyan often' },
          { value: 'minyan_sometimes', label: 'Minyan sometimes' },
          { value: 'alone_daily', label: 'Pray alone daily' },
          { value: 'irregular', label: 'Irregular' },
          { value: 'rarely', label: 'Rarely' },
        ],
      },
      {
        id: 3,
        question: 'How important is consistency in davening with a minyan to you?',
        type: 'likert',
        scale: 7,
        labels: ['Not important', 'Very important'],
      },
      {
        id: 4,
        question: 'What role does Torah learning play in your daily or weekly schedule?',
        type: 'enum',
        options: [
          { value: 'daily', label: 'Daily learning' },
          { value: 'several_weekly', label: 'Several times a week' },
          { value: 'weekly', label: 'Weekly' },
          { value: 'occasionally', label: 'Occasionally' },
          { value: 'minimal', label: 'Minimal' },
          { value: 'none', label: 'None' },
        ],
      },
      {
        id: 5,
        question: 'Do you currently learn regularly? If so, in what framework?',
        type: 'multiselect',
        options: [
          { value: 'yeshiva', label: 'Yeshiva' },
          { value: 'private_chavruta', label: 'Private chavruta' },
          { value: 'organized_class', label: 'Organized class' },
          { value: 'independent', label: 'Independent' },
          { value: 'not_learning', label: 'Not currently learning' },
        ],
      },
      {
        id: 6,
        question: 'How do you approach halachic questions or chumrot in daily life?',
        type: 'enum',
        options: [
          { value: 'ask_rabbi', label: 'Consult rabbi for everything' },
          { value: 'mostly_rabbi', label: 'Usually consult rabbi' },
          { value: 'case_by_case', label: 'Case by case' },
          { value: 'research_decide', label: 'Research and decide' },
          { value: 'lenient', label: 'Generally lenient' },
        ],
      },
      {
        id: 7,
        question: 'How do you observe Shabbat in your home?',
        type: 'enum',
        options: [
          { value: 'fully_observant', label: 'Fully observant' },
          { value: 'mostly_observant', label: 'Mostly observant' },
          { value: 'selectively_observant', label: 'Selectively observant' },
          { value: 'minimal', label: 'Minimal observance' },
          { value: 'cultural', label: 'Cultural only' },
        ],
      },
      {
        id: 8,
        question: 'What are your expectations around Shabbat atmosphere (guests, zemirot, rest)?',
        type: 'multiselect',
        options: [
          { value: 'guests_regular', label: 'Regular guests' },
          { value: 'guests_sometimes', label: 'Guests sometimes' },
          { value: 'quiet_intimate', label: 'Quiet and intimate' },
          { value: 'zemirot_singing', label: 'Zemirot and singing' },
          { value: 'focused_rest', label: 'Focused on rest' },
        ],
      },
      {
        id: 9,
        question: 'What kashrut standards do you personally keep?',
        type: 'enum',
        options: [
          { value: 'glatt_mehadrin', label: 'Glatt mehadrin' },
          { value: 'glatt_standard', label: 'Glatt standard' },
          { value: 'regular_kosher', label: 'Regular kosher' },
          { value: 'somewhat_flexible', label: 'Somewhat flexible' },
          { value: 'minimal', label: 'Minimal kashrut' },
        ],
      },
      {
        id: 10,
        question: 'How important is it that your spouse shares the same kashrut standards?',
        type: 'likert',
        scale: 7,
        labels: ['Not important', 'Very important'],
      },
      {
        id: 11,
        question: 'How do you relate to minhagim from your family or community?',
        type: 'enum',
        options: [
          { value: 'strict_adherence', label: 'Strict adherence' },
          { value: 'mostly_follow', label: 'Mostly follow' },
          { value: 'selective', label: 'Selective' },
          { value: 'flexible', label: 'Flexible' },
          { value: 'independent', label: 'Independent approach' },
        ],
      },
      {
        id: 12,
        question: 'How do you feel about integrating minhagim from a spouse\'s background?',
        type: 'likert',
        scale: 7,
        labels: ['Closed to it', 'Open to it'],
      },
      {
        id: 13,
        question: 'What does Yom Tov observance look like for you?',
        type: 'enum',
        options: [
          { value: 'very_strict', label: 'Very strict observance' },
          { value: 'traditional', label: 'Traditional' },
          { value: 'mostly_traditional', label: 'Mostly traditional' },
          { value: 'relaxed', label: 'Relaxed approach' },
          { value: 'minimal', label: 'Minimal' },
        ],
      },
      {
        id: 14,
        question: 'How central is religious growth to your vision of marriage?',
        type: 'likert',
        scale: 7,
        labels: ['Not central', 'Very central'],
      },
    ],
  },
  2: {
    title: 'Hashkafa & Values',
    questions: [
      {
        id: 15,
        question: 'How would you describe your general hashkafic outlook?',
        type: 'multiselect',
        options: [
          { value: 'yeshivish', label: 'Yeshivish' },
          { value: 'modern_orthodox', label: 'Modern Orthodox' },
          { value: 'chassidish', label: 'Chassidish' },
          { value: 'balanced', label: 'Balanced approach' },
          { value: 'other', label: 'Other/unique' },
        ],
      },
      {
        id: 16,
        question: 'What Torah values most strongly guide your life decisions?',
        type: 'multiselect',
        options: [
          { value: 'honesty', label: 'Honesty and integrity' },
          { value: 'family', label: 'Family first' },
          { value: 'community', label: 'Community responsibility' },
          { value: 'personal_growth', label: 'Personal growth' },
          { value: 'spirituality', label: 'Spirituality and closeness to God' },
        ],
      },
      {
        id: 17,
        question: 'How do you balance hishtadlut and bitachon in daily life?',
        type: 'likert',
        scale: 7,
        labels: ['More hishtadlut', 'More bitachon'],
      },
      {
        id: 18,
        question: 'What is your relationship with your rabbi or spiritual mentor?',
        type: 'enum',
        options: [
          { value: 'very_close', label: 'Very close, consult regularly' },
          { value: 'regular', label: 'Regular contact' },
          { value: 'occasional', label: 'Occasional contact' },
          { value: 'minimal', label: 'Minimal contact' },
          { value: 'none', label: 'No formal relationship' },
        ],
      },
      {
        id: 19,
        question: 'How important is alignment in hashkafa between spouses?',
        type: 'likert',
        scale: 7,
        labels: ['Not important', 'Very important'],
      },
      {
        id: 20,
        question: 'How do you view engagement with the broader (non-frum) world?',
        type: 'likert',
        scale: 7,
        labels: ['Very restricted', 'Very open'],
      },
      {
        id: 21,
        question: 'What role should community play in married life?',
        type: 'enum',
        options: [
          { value: 'central', label: 'Central to our life' },
          { value: 'important', label: 'Important' },
          { value: 'balanced', label: 'Balanced with privacy' },
          { value: 'minimal', label: 'Minimal involvement' },
          { value: 'independent', label: 'Independent from community' },
        ],
      },
      {
        id: 22,
        question: 'How do you feel about involvement in chesed or communal causes?',
        type: 'likert',
        scale: 7,
        labels: ['Not important', 'Very important'],
      },
      {
        id: 23,
        question: 'How do you approach personal growth and self-reflection?',
        type: 'enum',
        options: [
          { value: 'structured', label: 'Structured programs' },
          { value: 'regular', label: 'Regular practice' },
          { value: 'occasional', label: 'Occasional' },
          { value: 'minimal', label: 'Minimal focus' },
          { value: 'natural', label: 'Natural, as needed' },
        ],
      },
      {
        id: 24,
        question: 'What does "building a Torah home" mean to you personally?',
        type: 'multiselect',
        options: [
          { value: 'learning_environment', label: 'Learning and education' },
          { value: 'spirituality', label: 'Spirituality and values' },
          { value: 'community', label: 'Community engagement' },
          { value: 'warmth', label: 'Warmth and connection' },
          { value: 'tradition', label: 'Tradition and observance' },
        ],
      },
      {
        id: 25,
        question: 'How do you handle differences of opinion within a Torah framework?',
        type: 'enum',
        options: [
          { value: 'seek_guidance', label: 'Seek guidance from rabbi' },
          { value: 'discuss_respectfully', label: 'Discuss respectfully' },
          { value: 'agree_to_disagree', label: 'Agree to disagree' },
          { value: 'flexible', label: 'Flexible and open' },
          { value: 'defer_spouse', label: 'Defer to spouse' },
        ],
      },
      {
        id: 26,
        question: 'What values do you hope to transmit to your children?',
        type: 'multiselect',
        options: [
          { value: 'torah', label: 'Torah and observance' },
          { value: 'kindness', label: 'Kindness and compassion' },
          { value: 'integrity', label: 'Integrity' },
          { value: 'independence', label: 'Independence and thought' },
          { value: 'joy', label: 'Joy in Judaism' },
        ],
      },
    ],
  },
  3: {
    title: 'Learning, Career & Ambition',
    questions: [
      {
        id: 27,
        question: 'What is your current occupation or primary daily pursuit?',
        type: 'enum',
        options: [
          { value: 'learning_full_time', label: 'Learning full-time' },
          { value: 'professional', label: 'Professional career' },
          { value: 'business', label: 'Business/entrepreneurship' },
          { value: 'education', label: 'Education' },
          { value: 'healthcare', label: 'Healthcare' },
          { value: 'student', label: 'Student' },
          { value: 'transition', label: 'In transition' },
          { value: 'other', label: 'Other' },
        ],
      },
      {
        id: 28,
        question: 'How do you view the balance between Torah learning and parnassah?',
        type: 'enum',
        options: [
          { value: 'learning_priority', label: 'Learning is priority' },
          { value: 'learning_more', label: 'Learning more important' },
          { value: 'equal', label: 'Equally important' },
          { value: 'work_more', label: 'Work more important' },
          { value: 'work_priority', label: 'Work is priority' },
        ],
      },
      {
        id: 29,
        question: 'What are your long-term professional or learning goals?',
        type: 'multiselect',
        options: [
          { value: 'advanced_learning', label: 'Advanced Torah learning' },
          { value: 'career_advancement', label: 'Career advancement' },
          { value: 'stability', label: 'Financial stability' },
          { value: 'flexibility', label: 'Flexibility for family' },
          { value: 'impact', label: 'Making an impact' },
          { value: 'uncertain', label: 'Still figuring it out' },
        ],
      },
      {
        id: 30,
        question: 'How important is financial stability to you?',
        type: 'likert',
        scale: 7,
        labels: ['Not important', 'Very important'],
      },
      {
        id: 31,
        question: 'How do you envision financial responsibility within a marriage?',
        type: 'enum',
        options: [
          { value: 'man_provider', label: 'Man as primary provider' },
          { value: 'man_mostly', label: 'Man mostly provides' },
          { value: 'shared', label: 'Shared responsibility' },
          { value: 'woman_mostly', label: 'Woman mostly provides' },
          { value: 'flexible', label: 'Whatever works' },
        ],
      },
      {
        id: 32,
        question: 'What level of work-life balance do you hope to maintain?',
        type: 'enum',
        options: [
          { value: 'very_balanced', label: 'Very balanced (limited work)' },
          { value: 'mostly_balanced', label: 'Mostly balanced' },
          { value: 'moderate', label: 'Moderate balance' },
          { value: 'work_focused', label: 'Work-focused' },
          { value: 'very_work_focused', label: 'Very work-focused' },
        ],
      },
      {
        id: 33,
        question: 'How do you feel about a spouse pursuing advanced education or training?',
        type: 'likert',
        scale: 7,
        labels: ['Discouraging', 'Encouraging'],
      },
      {
        id: 34,
        question: 'How flexible are you regarding career changes over time?',
        type: 'likert',
        scale: 7,
        labels: ['Not flexible', 'Very flexible'],
      },
      {
        id: 35,
        question: 'What role does intellectual curiosity play in your life?',
        type: 'likert',
        scale: 7,
        labels: ['Not important', 'Very important'],
      },
      {
        id: 36,
        question: 'How do you continue learning outside of formal frameworks?',
        type: 'multiselect',
        options: [
          { value: 'reading', label: 'Reading and study' },
          { value: 'podcasts', label: 'Podcasts and media' },
          { value: 'informal', label: 'Informal discussions' },
          { value: 'minimal', label: 'Minimal' },
          { value: 'other', label: 'Other methods' },
        ],
      },
      {
        id: 37,
        question: 'How important is ambition or drive in a spouse?',
        type: 'likert',
        scale: 7,
        labels: ['Not important', 'Very important'],
      },
      {
        id: 38,
        question: 'How do you define success at this stage of life?',
        type: 'multiselect',
        options: [
          { value: 'spiritual', label: 'Spiritual growth' },
          { value: 'career', label: 'Career achievement' },
          { value: 'family', label: 'Family building' },
          { value: 'financial', label: 'Financial success' },
          { value: 'happiness', label: 'Happiness and contentment' },
        ],
      },
    ],
  },
  4: {
    title: 'Lifestyle & Personality',
    questions: [
      {
        id: 39,
        question: 'How would friends describe your personality?',
        type: 'multiselect',
        options: [
          { value: 'outgoing', label: 'Outgoing and social' },
          { value: 'thoughtful', label: 'Thoughtful and reflective' },
          { value: 'fun_loving', label: 'Fun-loving' },
          { value: 'serious', label: 'Serious and focused' },
          { value: 'warm', label: 'Warm and empathetic' },
        ],
      },
      {
        id: 40,
        question: 'Do you recharge more through social interaction or quiet time?',
        type: 'likert',
        scale: 7,
        labels: ['Quiet time', 'Social interaction'],
      },
      {
        id: 41,
        question: 'How do you typically spend your free time?',
        type: 'multiselect',
        options: [
          { value: 'with_friends', label: 'Time with friends' },
          { value: 'family', label: 'Family time' },
          { value: 'hobbies', label: 'Hobbies and interests' },
          { value: 'outdoor', label: 'Outdoor activities' },
          { value: 'relaxing', label: 'Relaxing and resting' },
        ],
      },
      {
        id: 42,
        question: 'What hobbies or interests are important to you?',
        type: 'multiselect',
        options: [
          { value: 'sports', label: 'Sports or fitness' },
          { value: 'arts', label: 'Arts or music' },
          { value: 'reading', label: 'Reading' },
          { value: 'outdoors', label: 'Outdoor activities' },
          { value: 'technology', label: 'Technology' },
          { value: 'cooking', label: 'Cooking' },
          { value: 'travel', label: 'Travel' },
        ],
      },
      {
        id: 43,
        question: 'How structured or spontaneous is your daily routine?',
        type: 'likert',
        scale: 7,
        labels: ['Very structured', 'Very spontaneous'],
      },
      {
        id: 44,
        question: 'How do you handle stress or pressure?',
        type: 'enum',
        options: [
          { value: 'internal', label: 'Process internally' },
          { value: 'talk_it_out', label: 'Talk it out' },
          { value: 'physical', label: 'Physical activity' },
          { value: 'spiritual', label: 'Spiritual practice' },
          { value: 'compartmentalize', label: 'Compartmentalize' },
        ],
      },
      {
        id: 45,
        question: 'How expressive are you emotionally?',
        type: 'likert',
        scale: 7,
        labels: ['Reserved', 'Very expressive'],
      },
      {
        id: 46,
        question: 'How do you prefer to give and receive support?',
        type: 'multiselect',
        options: [
          { value: 'listening', label: 'Listening and empathy' },
          { value: 'practical', label: 'Practical help' },
          { value: 'words', label: 'Words of encouragement' },
          { value: 'space', label: 'Give space and independence' },
          { value: 'presence', label: 'Just being present' },
        ],
      },
      {
        id: 47,
        question: 'How important is humor in your relationships?',
        type: 'likert',
        scale: 7,
        labels: ['Not important', 'Very important'],
      },
      {
        id: 48,
        question: 'How do you approach planning versus flexibility?',
        type: 'likert',
        scale: 7,
        labels: ['Very planned', 'Very flexible'],
      },
      {
        id: 49,
        question: 'How do you typically resolve interpersonal tension?',
        type: 'enum',
        options: [
          { value: 'direct', label: 'Address directly' },
          { value: 'thoughtful', label: 'Thoughtful conversation' },
          { value: 'time', label: 'Give it time' },
          { value: 'involve_other', label: 'Involve third party' },
          { value: 'avoid', label: 'Tend to avoid' },
        ],
      },
      {
        id: 50,
        question: 'What qualities do you most value in close relationships?',
        type: 'multiselect',
        options: [
          { value: 'trust', label: 'Trust and honesty' },
          { value: 'humor', label: 'Humor and fun' },
          { value: 'depth', label: 'Depth and meaning' },
          { value: 'support', label: 'Support and loyalty' },
          { value: 'independence', label: 'Respect for independence' },
        ],
      },
    ],
  },
  5: {
    title: 'Marriage, Home & Family Vision',
    questions: [
      {
        id: 51,
        question: 'What does a successful marriage look like to you?',
        type: 'multiselect',
        options: [
          { value: 'partnership', label: 'True partnership' },
          { value: 'growth', label: 'Mutual growth' },
          { value: 'joy', label: 'Joy and laughter' },
          { value: 'support', label: 'Emotional support' },
          { value: 'commitment', label: 'Lifetime commitment' },
        ],
      },
      {
        id: 52,
        question: 'How do you envision dividing responsibilities in a home?',
        type: 'enum',
        options: [
          { value: 'traditional', label: 'Traditional roles' },
          { value: 'mostly_traditional', label: 'Mostly traditional' },
          { value: 'flexible', label: 'Flexible and responsive' },
          { value: 'equal', label: 'Equally shared' },
          { value: 'individual', label: 'Based on individual strengths' },
        ],
      },
      {
        id: 53,
        question: 'How do you approach decision-making as a couple?',
        type: 'enum',
        options: [
          { value: 'husband_leads', label: 'Husband leads' },
          { value: 'mostly_husband', label: 'Mostly husband' },
          { value: 'collaborative', label: 'Collaborative' },
          { value: 'equal', label: 'Equal partnership' },
          { value: 'situational', label: 'Situational' },
        ],
      },
      {
        id: 54,
        question: 'How important is open communication in a marriage to you?',
        type: 'likert',
        scale: 7,
        labels: ['Not important', 'Very important'],
      },
      {
        id: 55,
        question: 'How do you handle disagreements or conflict?',
        type: 'enum',
        options: [
          { value: 'seek_resolution', label: 'Seek quick resolution' },
          { value: 'thoughtful_discussion', label: 'Thoughtful discussion' },
          { value: 'take_time', label: 'Take time before discussing' },
          { value: 'involve_rabbi', label: 'Involve rabbi or counselor' },
          { value: 'accept_differences', label: 'Accept and move on' },
        ],
      },
      {
        id: 56,
        question: 'What role should extended family play in married life?',
        type: 'enum',
        options: [
          { value: 'very_involved', label: 'Very involved' },
          { value: 'involved', label: 'Involved' },
          { value: 'balanced', label: 'Balanced involvement' },
          { value: 'minimal', label: 'Minimal involvement' },
          { value: 'separate', label: 'Separate from extended family' },
        ],
      },
      {
        id: 57,
        question: 'How do you feel about geographic flexibility after marriage?',
        type: 'likert',
        scale: 7,
        labels: ['Want to stay put', 'Open to relocation'],
      },
      {
        id: 58,
        question: 'What are your hopes regarding children?',
        type: 'enum',
        options: [
          { value: 'yes_many', label: 'Yes, many children' },
          { value: 'yes_several', label: 'Yes, several children' },
          { value: 'yes_few', label: 'Yes, a few children' },
          { value: 'maybe', label: 'Maybe, not sure' },
          { value: 'no', label: 'No children' },
        ],
      },
      {
        id: 59,
        question: 'How do you approach chinuch and parenting in theory?',
        type: 'multiselect',
        options: [
          { value: 'religious_education', label: 'Strong religious education' },
          { value: 'secular_education', label: 'Good secular education' },
          { value: 'values', label: 'Values and character' },
          { value: 'independence', label: 'Independence and critical thinking' },
          { value: 'happiness', label: 'Happiness and fulfillment' },
        ],
      },
      {
        id: 60,
        question: 'What kind of home environment do you hope to create?',
        type: 'multiselect',
        options: [
          { value: 'warm', label: 'Warm and welcoming' },
          { value: 'structured', label: 'Structured and organized' },
          { value: 'intellectual', label: 'Intellectually stimulating' },
          { value: 'spiritual', label: 'Spiritually rich' },
          { value: 'fun', label: 'Fun and joyful' },
        ],
      },
    ],
  },
  6: {
    title: 'Compatibility & Reflection',
    questions: [
      {
        id: 61,
        question: 'What qualities are you actively working to improve in yourself?',
        type: 'multiselect',
        options: [
          { value: 'patience', label: 'Patience' },
          { value: 'communication', label: 'Communication skills' },
          { value: 'emotional_awareness', label: 'Emotional awareness' },
          { value: 'organization', label: 'Organization' },
          { value: 'compassion', label: 'Compassion' },
          { value: 'other', label: 'Other areas' },
        ],
      },
      {
        id: 62,
        question: 'What traits are essential for you in a spouse?',
        type: 'multiselect',
        options: [
          { value: 'honesty', label: 'Honesty and integrity' },
          { value: 'kindness', label: 'Kindness' },
          { value: 'intelligence', label: 'Intelligence' },
          { value: 'sense_of_humor', label: 'Sense of humor' },
          { value: 'shared_values', label: 'Shared values' },
          { value: 'emotional_maturity', label: 'Emotional maturity' },
        ],
      },
      {
        id: 63,
        question: 'What differences in a spouse feel manageable or even positive?',
        type: 'multiselect',
        options: [
          { value: 'personality', label: 'Different personalities' },
          { value: 'interests', label: 'Different interests' },
          { value: 'background', label: 'Different backgrounds' },
          { value: 'communication_style', label: 'Different communication styles' },
          { value: 'hashkafa_nuance', label: 'Nuanced hashkafa differences' },
        ],
      },
      {
        id: 64,
        question: 'What kinds of differences would be difficult for you?',
        type: 'multiselect',
        options: [
          { value: 'religious_level', label: 'Religious observance level' },
          { value: 'values', label: 'Core values' },
          { value: 'life_goals', label: 'Life goals and vision' },
          { value: 'family_plans', label: 'Family planning' },
          { value: 'honesty', label: 'Honesty and trustworthiness' },
        ],
      },
      {
        id: 65,
        question: 'What excites you most about the idea of marriage?',
        type: 'multiselect',
        options: [
          { value: 'partnership', label: 'Having a true partner' },
          { value: 'family', label: 'Building a family' },
          { value: 'growth', label: 'Personal and spiritual growth' },
          { value: 'companionship', label: 'Companionship and intimacy' },
          { value: 'shared_life', label: 'Sharing a meaningful life' },
        ],
      },
      {
        id: 66,
        question: 'Is there anything important about you that hasn\'t been asked but should be known?',
        type: 'text',
        maxLength: 500,
      },
    ],
  },
};

module.exports = surveyQuestions;
